baseURL = "https://veslo5.github.io/Devlair/"
languageCode = "cs-cz"
title = "Devlair"
theme = "DDevLair"
relativeURLs = "true"
canonifyURLs = "true"
[menu]
  [[menu.main]]
    name = "home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blog"
    pre = ""
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "projekty"
    pre = ""
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "o mnÄ›"
    pre = ""
    url = "/aboutme/"
    weight = 4